### PR TITLE
proposal to link to vis.js repository

### PR DESCRIPTION
**Pull request by kixam**
hi,

I propose to use the vis.js repository as a submodule of your plugin, so that it is easier to get updates, it is less redundant (no static hard copy), and I think it is more elegant.

### CODE REVIEW

**Comment by felixhayashi** [comment]
Hi Kixam,

Thanks for your proposal :)

>  it is less redundant (no static hard copy), and I think it is more elegant.

I agree that it is more elegant.

Problem here is that I changed the colors of the original network buttons that appear in the graph's canvas from green to gray to be more visually fitting and less distracting when used in tiddlywiki.

>> Other than that, I personally find the button colors distracting and would rather go with something grey, google earth style... with the button borders being smaller.

> I agree. It sucks that the buttons are png and I cannot change the color so I think I have to open Photoshop and change them to gray one by one manually.

> https://github.com/felixhayashi/TW5-TiddlyMap/issues/28#issuecomment-71815101

Also, unfortunately, I cannot change to 4.0 right away because of major api changes in 4.0.

https://groups.google.com/d/msg/tiddlywikidev/_HI4fTfOtO8/Hkg64ZhMhrsJ

Also 4.0 (as any major release of this complexity) still has flaws and mistakes and there will be many patches released in the next weeks...

-Felix

**Comment by kixam** [comment]
> Problem here is that I changed the colors of the original network buttons that appear in the graph's canvas from green to gray to be more visually fitting and less distracting when used in tiddlywiki.

I agree, your icons are more beautiful. I committed a restorer. But what do you think of getting vis.js and vis.css from a submodule?

> Also, unfortunately, I cannot change to 4.0 right away because of major api changes in 4.0.

I understand. Please feel free to pull any time you want - or just close the request if you do not like my proposal !

**Comment by felixhayashi** [comment]
HI @kixam 

> I agree, your icons are more beautiful.

:) Maybe it is possible to offer two styled versions so it is still possible to use vis.js as submodule as you proposed it

> But what do you think of getting vis.js and vis.css from a submodule?

as said, I think it is more elegant :)

I thought about using wget in the build.sh script and download the zipped repo then unpack it and extract the images and files. But your solution looks better at the moment.

> I understand. Please feel free to pull any time you want - or just close the request if you do not like my proposal ! :)

I'll wait with changing the vis repo until I am done with all the v4 work at tiddlymap. Sorry if it will take a while but I am also working on my master thesis (still a student) and this consumes some time :(

-Felix

**Comment by kixam** [comment]
Hi @felixhayashi ,

> I'll wait with changing the vis repo until I am done with all the v4 work at tiddlymap
did you change your mind about this ?

**Comment by felixhayashi** [comment]
Hi @kixam 

at the moment, I do not want to change it. I think its better to close the PR for now. Once I have more time, I'll improve the way the "dist" is generated, probably the way you suggested it, but not sure at the moment...

-Felix

**Pull request closed without merging**
