### PR TITLE
v4.11.0 using almende/vis repo as submodule + implement bug avoiding code where it belongs

### PR DESCRIPTION
**Pull request by kixam**
hi @felixhayashi and happy new year,

I would like to offer this new pull request which contains:
* a cleaner way to link almende/vis repo as a submodule compared to my first proposal;
*  your own code resolving both https://github.com/felixhayashi/TW5-TiddlyMap/issues/163 and https://github.com/kixam/TW5-visjsTimeline/issues/20 , only put where it belongs
* a hot fix for https://github.com/almende/vis/issues/1527

kixam

### CODE REVIEW

**Comment by felixhayashi** [comment]
Hi @kixam. Bonne année.

Very nice PR, thanks!

I'll merge it and add the follwing line at the beginning of the script:

    git submodule update --init --recursive

so the script won't fail if users clone the repo without fetching the submodule.

-Felix

**Comment by kixam** [comment]
hi @felixhayashi ,

Thank you for merging.

2 remarks:
* if you include `git submodule update --init --recursive` in build.sh, then you might want to implement some code to read the updated version of Vis.js : ```latestTag = $(git describe --tags `git rev-list --tags --max-count=1`) ``` and update plugin.info accordingly

* I think you ran build.sh and thus updated dist/.../vis.js again. If so, you might have reintroduced the https://github.com/almende/vis/issues/1527 bug, because I made a hotfix on the dist file and not on the original file. I guess this is the drawback of using `submodule` ... Users of visTimeline plugin can download Vis.js v4.11.0 with the hotfix on the [visTimeline demo website](http://kixam.github.io/TW5-visjsTimeline/). I guess you could also check out the develop branch up to the [official fix](https://github.com/almende/vis/commit/4cae296b1779d85b57b34c2ca01ebaedb44bd92e), this is the first code-modifying commit after the release

**Comment by felixhayashi** [comment]
Hi @kixam 

> I think you ran build.sh and thus updated dist/.../vis.js again. If so, you might have reintroduced the almende/vis#1527 bug

woops sorry didn't notice will add it again.

> latestTag = $(git describe --tags `git rev-list --tags --max-count=1`)

I think we should handle this manually since we may do manual hotfixes to the files and increment the version by hand?

-Felix

**Comment by kixam** [comment]
> I think we should handle this manually since we may do manual hotfixes to the files and increment the version by hand?

I think so, but then so goes for the subtree update. I see you commented that out in build.sh so I guess you agree.

**Comment by felixhayashi** [comment]
> I think so, but then so goes for the subtree update. I see you commented that out in build.sh so I guess you agree.

Yes, I do. I think it is better to add instructions to the readme.md on how to compile ones own plugin and how to download the latest visjs. By the way, next visjs will be released on friday, and I'll bump our version then to the master branch again.

**Pull request merged**
